# Generated by Django 4.2.3 on 2023-07-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enoid_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='TourDate',
        ),
    ]
