# Generated by Django 4.2.3 on 2023-07-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enoid_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdate',
            name='image_url',
            field=models.URLField(default='/static/images/default-image.jpg'),
        ),
        migrations.AddField(
            model_name='tourdate',
            name='tickets_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
